Silex 2
graze/silex-trailing-slash-handler pull request #9
Opened 2017-09-21 21:09 UTC by hkdobrev

Add Silex 2 support.
Closes #8.

2017-09-21 22:59 UTC, asiviero commented
wouldn't this break backwards compatibility?

2017-09-22 07:27 UTC, hkdobrev commented
@asiviero Definitely! This should be released as a new minor version `0.2.0` (according to semver rules when the major version is still `0`) or you could release it as `1.0.0`.

However, this would allow users of Silex 2 which has been out for some time to use the provider.

2017-09-22 10:46 UTC, h-bragg requested changes
Hi! 

Thanks for the PR! Excellent stuff. 

I expect we would bump this to 1.0 just to be clear.

the `--prefer-lowest --prefer-stable` test on travis is failing. 

you can run:

```shell
make 'composer-update --prefer-lowest --prefer-stable'
make test-unit
```

locally to test. 

I expect:

```diff
     "require-dev": {
          "mockery/mockery": "^0.9.4",
 -        "phpunit/phpunit": "^5.0",
 +        "phpunit/phpunit": "^5.1.1",
          "roave/security-advisories": "dev-master"
      },
```

would fix the issue.

Or I have created a PR: #10 that should help.

2017-09-22 10:46 UTC, h-bragg commented on src/TrailingSlashControllerProvider.php
> +                $app['request_stack']->getCurrentRequest()->getMethod(),
Looks like it is worth extracting `$app['request_stack']->getCurrentRequest()` into a variable now

2017-09-22 15:12 UTC, asiviero commented
@hkdobrev sure, a version bump might be in order, just wanted to highlight it

2017-09-24 18:56 UTC, hkdobrev commented
@asiviero @h-bragg Changes made!

The tests were passing locally for me even when I run the docker container and install the lowest deps.

BTW if you want to continue supporting Silex 1 with bugfixes, you might want to release 1.0 for an earlier commit, release 2.0 with this and then have a branch for 1.x.

2017-09-24 19:03 UTC, hkdobrev commented
Tests on Travis CI are still failing 😞 Are they failing for you locally?

2017-09-25 09:47 UTC, h-bragg commented
Running this locally I get:

```
[10:07] ~/git/silex-trailing-slash-handler ● make 'composer-update --prefer-stable --prefer-dist --prefer-lowest'
...
[10:13] ~/git/silex-trailing-slash-handler ● make test
docker run --rm -it -v $(pwd):/opt/graze/silex-trailing-slash-handler graze/silex-trailing-slash-handler \
	composer test --ansi
Do not run Composer as root/super user! See https://getcomposer.org/root for details
> vendor/bin/phpunit --colors=always tests/
PHPUnit 5.1.1 by Sebastian Bergmann and contributors.

...............................
Fatal error: Call to undefined method Symfony\Component\Debug\ExceptionHandler::getHtml() in /opt/graze/silex-trailing-slash-handler/vendor/silex/silex/src/Silex/ExceptionHandler.php on line 44
Script vendor/bin/phpunit --colors=always tests/ handling the test event returned with error code 255
make: *** [test-unit] Error 255
```

I guess something else needs updating to a minimum version

2017-09-25 09:49 UTC, h-bragg commented
I have updated the master branch with my PR to improve travis and the Makefile.

Might be a few changes to rebase in, but hopefully should help with testing.

`make test-matrix-lowest`

will then test with the lowest allowed dependency versions.

2017-09-25 11:34 UTC, h-bragg commented
Looks like the problem is that it uses `symfony/debug` version 2.8. But it only explicitly requires `http-kernel` (for non dev) which requires `debug >= 2.6`.

the `->getHtml` was added in `2.8` which is in their `require-dev` group.

Adding `        "symfony/debug": "~2.8|^3.0"` into `require-dev` makes it all work again.

2017-09-25 14:28 UTC, hkdobrev commented
@h-bragg Thanks for the insight!

2017-09-25 15:25 UTC, h-bragg submitted a review, later dismissed

2017-09-25 16:26 UTC, h-bragg commented
Released the current master to v1. And created a `1.x` branch for future development.

This has changed another file, added a test.

Will merge this and release v2 with when it is rebased.

Cheers for the PR and fixes!

2017-09-25 16:28 UTC, hkdobrev commented
Done.

2017-09-25 17:11 UTC, h-bragg commented
Looks like the logging test has broken this. Does it not call `url_matcher` in silex 2 any more?

2017-09-25 18:10 UTC, hkdobrev commented
I'd look into it. I had some conflicts around that.

2017-09-26 08:40 UTC, h-bragg commented
Looks like they renamed `url_matcher` to `request_matcher`.

The following patch fixes this and adds a test to ensure it 404's for `/` routes instead of `301` which is default (to ensure the request_matcher is being overridden).

[patch.txt](https://github.com/graze/silex-trailing-slash-handler/files/1332329/patch.txt)

2017-09-26 09:17 UTC, h-bragg approved these changes

2017-09-26 09:17 UTC, merged

2017-09-26 09:23 UTC, hkdobrev commented
@h-bragg Thanks for the insights and help!